.DEFAULT_GOAL=all

ARCH	:= $(shell 	uname -m)
TARGET	:= $(shell basename $(CURDIR))
BUILDIR :=

SRC		:= src
BUILD	:= build
INSTALL	:= install
PACKAGE	:= package
JOBS    := $(shell nproc)

ifndef VERBOSE
MAKEFLAGS += --no-print-directory
endif
